apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.phoenix.name }}
spec:
  {{- if .Values.phoenix.replicas }}
  replicas: {{ .Values.phoenix.replicas }}
  {{- else }}
  replicas: 1
  {{- end }}  
  template:
    spec:
      containers:
        - name: {{ .Values.phoenix.name }}
          image: "{{ .Values.phoenix.image.repository }}:{{ .Values.phoenix.image.tag }}"
          ports:
            - containerPort: {{ .Values.phoenix.containerPort }}