apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.phoenix.name }}
spec:
  selector:
    app: {{ .Values.phoenix.name }}
  ports:
    - name: otlp
      port: {{ .Values.phoenix.containerPort }}
      targetPort: {{ .Values.phoenix.containerPort }}