apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoenix.name" . }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: otlp
      port: {{ .Values.phoenix.ports.otlp }}
      targetPort: otlp
      protocol: TCP
    - name: ui
      port: {{ .Values.phoenix.ports.ui }}
      targetPort: ui
      protocol: TCP
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}