apiVersion: v2
name: search-agent
description: A Helm chart deploying an OpenAI search agent with Tavily tools
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: '18.2.3'
    repository: 'https://charts.bitnami.com/bitnami'
